
# DATABASE CONFIGURATION

spring.datasource.url=jdbc:postgresql://localhost:5432/salarydb
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA / HIBERNATE CONFIGURATION

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# LOGGING CONFIGURATION
# Show SQL statements in console
logging.level.org.hibernate.SQL=DEBUG

# Show parameter values used in SQL queries
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Show when tables are created/updated
logging.level.org.hibernate.tool.hbm2ddl=DEBUG

# Spring Web logs (optional but helpful)
logging.level.org.springframework.web=INFO

# DataSource and connection pool logs (optional)
logging.level.org.springframework.jdbc.core=DEBUG

# Root level logging (INFO by default; can set to DEBUG)
logging.level.root=INFO

# JWT CONFIGURATION
jwt.secret=MySuperSecretKeyForSalaryManagementSystem12345678
jwt.expiration=86400000
